apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: qdrouterds.ajssmith.github.io
spec:
  group: ajssmith.github.io
  names:
    kind: Qdrouterd
    listKind: QdrouterdList
    plural: qdrouterds
    singular: qdrouterd
    shortNames:
    - qdr
  scope: Namespaced
  version: v1alpha1
